name: comiko
description: Comiko

dependencies:
  flutter:
    sdk: flutter
  redux: "^2.0.1"
  flutter_redux: "^0.3.1"
  path: "^1.4.2"
  comiko_shared:
    git: https://github.com/comiko-app/shared.git
  comiko_backend:
    git: https://github.com/comiko-app/backend.git
  firebase_firestore: '>=0.0.1+1 <0.1.0'
  font_awesome_flutter: '>=4.7.2 <5.0.0'
  url_launcher: "^0.4.2+5"
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/martin-matte1.jpg
    - lib/assets/guillaume-wagner1.jpg
    - lib/assets/jean-marc-parent-v3.jpg
    - lib/assets/adib-alkhalidey-1.jpg
    - lib/assets/dominic-et-martin1.jpg
    - lib/assets/dominic-paquet1.jpg
    - lib/assets/fabien-cloutier1.jpg
    - lib/assets/jean-michel-anctil1.jpg
    - lib/assets/jrmy-demay1.jpg
    - lib/assets/katerine-levac1.jpg
    - lib/assets/les-grandes-crues1.jpg
    - lib/assets/louis-t1.jpg
    - lib/assets/marianna-mazza1.jpg
    - lib/assets/pierre-hbert1.jpg
    - lib/assets/ral-bland1.jpg
    - lib/assets/simon-leblanc1.jpg
    - lib/assets/alexroof.jpg
    - lib/assets/mathieucyr.jpg
    - lib/assets/julienlacroix.jpg
    - lib/assets/jaydutemple.jpg
    - lib/assets/comiko.png
    - lib/assets/comiko_white.png
    - lib/assets/comiko_logo.png
    - lib/data/events.json

  fonts:
    - family: FontAwesome # Do not change!
      fonts:
        - asset: packages/font_awesome_flutter/fonts/fontawesome.woff

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
